- everest/detached/__init__.py
- tests/test_detached.py
Replaced job_progress.jobs  with job_progress.steps
> Missed instance of job_progress.jobs

- everest/bin/everest_script.py
**Issue**
Closes #11 
**Approach**
Reuse context manager
> Ensure site-config is active when making ert config

- docs/source/config_generated.rst
- everest/config/control_config.py
- everest/config/control_variable_config.py
- everest/optimizer/everest2ropt.py
- tests/test_fix_control.py
**Issue**
Allow fixed variables in the optimization
Closes #17
> Add enabled option to controls to allow fixing them

- everest/optimizer/ropt_plugins.py
- pyproject.toml
**Issue**
Update to adjust for minor changes in ropt.
**Approach**
Change two base class names, update `rop` and `ropt-dakota`.
> Updates for ropt 0.4.0

- everest/api/everest_data_api.py
- everest/bin/everload_script.py
- everest/simulator/simulator.py
- tests/test_api.py
- tests/unit/everest/bin/test_everload.py
**Issue**
Also some cleanup after https://github.com/equinor/everest/commit/60ff8e6665b8fbaefbad0769a9da684d0eb0ac98
> Remove dependency on LibreFacade where it was not strictly necessary.

- everest/config/validation_utils.py
- everest/plugins/hook_impl.py
- everest/plugins/hook_specs.py
- everest/util/forward_models.py
- tests/test_fm_plugins.py
**Issue**
Running into pydantic errors when trying to validate forward model job file arguments (specifically well swapping)  which uses the new standard 
**Approach**
No error when validating forward models
> Accept the new everest-models hook for linting forward models

- everest/detached/__init__.py
- everest/simulator/simulator.py
- everest/suite.py
**Issue**
_Short description of the issue_
Closes #_XXX_
**Approach**
_Short description of the approach_
> Cleanup some interaction with ert

- everest/jobs/__init__.py
- everest/plugins/hook_impl.py
- everest/plugins/site_config_env.py
- tests/test_site_config_env.py
> Remove dependency on ert's internal fmsteps

- everest/bin/main.py
Using scheduler is only valid option on main now
> Do not used deprecated feature toggle

- .github/workflows/mac-run-tests-build-docs.yml
- .github/workflows/run-tests-build-docs.yml
- everest/util/forward_models.py
- pyproject.toml
- tests/functional/test_main_everest_entry.py
- tests/test_egg_simulation.py
- tests/test_res_initialization.py
- tests/test_workflows.py
- tests/test_yaml_parser.py
- tests/utils/__init__.py
**Issue**
Closes #46
**Approach**
- Make math test run without everest-models
> Everest should be independent of everest-models

- docs/source/cli.rst
- everest/bin/everconfigdump_script.py
- everest/bin/everest_script.py
- everest/bin/everexport_script.py
- everest/bin/everlint_script.py
- everest/bin/everload_script.py
- everest/bin/kill_script.py
- everest/bin/main.py
- everest/bin/monitor_script.py
- everest/bin/visualization_script.py
- ieverest/bin/ieverest_script.py
Use args_parser information to generate the commands documentation
Closes #51
> Auto-generate documentation for the CLI

- .github/workflows/mac-run-tests-build-docs.yml
**Issue**
Fix tests running when tag is created
> Fix macos tests

- everest/simulator/simulator.py
> Remove no longer needed folder switching.

- everest/optimizer/everest2ropt.py
Upper bound was called lower bound and vice versa
> Fixup wrong variable naming

- src/everest/bin/everload_script.py
- src/everest/simulator/everest_to_ert.py
- src/everest/simulator/simulator.py
- tests/test_detached.py
- tests/test_egg_simulation.py
- tests/test_environment.py
- tests/test_multiobjective.py
- tests/test_res_initialization.py
- tests/test_yaml_parser.py
> Rename everest2res to everest_to_ert_config

- src/ieverest/utils.py
> Remove app_main_window no longer used.

- .github/workflows/coverage.yml
- pyproject.toml
> Add test code coverage

- src/everest/detached/__init__.py
- src/everest/suite.py
- tests/test_detached.py
Blocked by https://github.com/equinor/ert/pull/8389
> Remove import of ert.JobStatus

- tests/entry_points/test_everest_entry.py
> Add test for ieverest_entry

- tests/test_export_data_dialog.py
**Issue**
Closes #92 
```
---------------------------------------------------------------------------
src/ieverest/__init__.py                          3      0   100%
src/ieverest/bin/__init__.py                      0      0   100%
src/ieverest/bin/ieverest_script.py              29     19    34%   16-36, 41-54, 58
src/ieverest/config_widget.py                    17      0   100%
src/ieverest/ieverest.py                        198     64    68%   49-71, 74-76, 79-81, 116, 139-143, 150-154, 158, 173, 176-185, 191-201, 203-207, 213-239, 242-245, 249, 289-291, 308, 310, 316
src/ieverest/io/__init__.py                       4      0   100%
src/ieverest/io/output_dispatcher.py             33      3    91%   30-31, 45
src/ieverest/io/qt_dialogs_output.py             19      0   100% …
```
> Add tests for export data dialog

- pyproject.toml
- src/everest/api/everest_data_api.py
- src/everest/bin/everload_script.py
- src/everest/export.py
- tests/test_api.py
**Issue**
Waiting for  https://github.com/equinor/ert/pull/8623 before review and merge
> Handel no more direct access to ensemble by name from storage.

- pyproject.toml
- src/everest/suite.py
**Issue**
The code interfacing with `ropt `needs updating, simplifying it.
> Update to ropt 0.6.0

- tests/conftest.py
> Set offscreen for tests

- tests/test_egg_simulation.py
**Issue**
Change the tmp_dir logic to be able to specify path in worlflows
> Change tmp dir for egg snapshot test

- tests/test_egg_simulation.py
**Issue**
_Short description of the issue_
Closes #_XXX_
**Approach**
_Short description of the approach_
> Add monkeypatch

- tests/test_egg_simulation.py
**Issue**
_Short description of the issue_
Closes #_XXX_
**Approach**
_Short description of the approach_
> Fix egg snapshot test

- tests/test_egg_simulation.py
> Apply autostyling test_egg_simulation.py

- ci/testkomodo.sh
Pylintrc does not exist anymore
> Remove copying of pylintrc file

- tests/everest/entry_points/test_everest_entry.py
- tests/everest/entry_points/test_everexport.py
- tests/everest/test_detached.py
- tests/everest/utils/__init__.py
> Replace capture_logger with caplog

- examples/math_func/config_advanced.yml
- src/everest/bin/config_branch_script.py
- src/everest/config_file_loader.py
- tests/everest/entry_points/test_config_branch_entry.py
> Preserve config order when using branch entry

- pyproject.toml
**Issue**
New rc for everest does not have the right ropt dependencies
**Approach**
Update dependencies
> Update ropt depencencies

- .readthedocs.yaml
- docs/everest/conf.py
**Issue**
Related to https://github.com/equinor/ert/issues/8806
While moving the process or building the Everest documentation from the ert repo we should at least fix the current build.
> Fix read the docs build
